# Generated by Django 2.1.7 on 2019-03-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=50)),
                ('isSpeaker', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateStart', models.DateField()),
                ('dateStop', models.DateField()),
                ('abstractDeadline', models.DateField()),
                ('submitDeadline', models.DateField()),
                ('bidDeadline', models.DateField()),
                ('reviewDeadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=50)),
                ('webpage', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyWords', models.CharField(max_length=100)),
                ('abstract', models.FileField(upload_to='pdf')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('isAccepted', models.BooleanField(default=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(choices=[('strong accept', 'strong accept'), ('accept', 'accept'), ('weak accept', 'weak accept'), ('borderline paper', 'borderline paper'), ('weak reject', 'weak reject'), ('reject', 'reject'), ('strong reject', 'strong reject')], default=False, max_length=15)),
                ('suggestions', models.TextField()),
                ('prid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramCommitteeMember')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chair')),
                ('confid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='WIshToReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'yes'), ('maybe', 'maybe'), ('no', 'no')], default=False, max_length=6)),
                ('prid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proposal')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reviewer')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reviewer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
        migrations.AddField(
            model_name='programcommittee',
            name='pcid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramCommitteeMember'),
        ),
        migrations.AddField(
            model_name='chair',
            name='pcid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramCommitteeMember'),
        ),
    ]
