# Generated by Django 2.1.7 on 2019-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190409_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
    ]
